### ISSUE TITLE
Invalid return types (triples and contexts method)

### ISSUE THREAD

**Issue by lukasmu** [oxigraph/oxrdflib#29]
I just discovered two occasions where the methods of the oxrdflib's store do not return objects of the correct type.

**1. triples method:**
Return type should be `Iterator[Tuple[_Triple, Iterator[Optional[Graph]]]]`. This method actually returns something like `Iterator[Tuple[_Triple, Optional[rdflib.IdentifiedNode]]]` (the second element of the tuple is neither an iterator nor does it contain graphs): 
https://github.com/oxigraph/oxrdflib/blob/08178edd5033a7cb4de0fe6bf7d3e9f38feb7b2d/oxrdflib/__init__.py#L84-L89

**2. contexts method**:
Return type should be `Generator[Graph, None, None]`. The method actually returns something like `Generator[rdflib.IdentifiedNode, None, None]`:
https://github.com/oxigraph/oxrdflib/blob/08178edd5033a7cb4de0fe6bf7d3e9f38feb7b2d/oxrdflib/__init__.py#L97-L100

The type hints in oxrdflib are correct as far as I can see (they are inline with the type hints in rdflib.store). 
I fear that fixing this bug requires some non-trivial changes.

Here's a demo of the issue:
```
import rdflib
import rdflib.plugins.stores.memory
import oxrdflib

store_memory = rdflib.plugins.stores.memory.Memory()
store_oxigraph = oxrdflib.OxigraphStore()

graph_memory = rdflib.ConjunctiveGraph(store=store_memory)
graph_oxigraph = rdflib.ConjunctiveGraph(store=store_oxigraph)

graph_memory.add((rdflib.URIRef("http://localhost/test"),  rdflib.RDF.value, rdflib.Literal("abc")))
graph_oxigraph.add((rdflib.URIRef("http://localhost/test"),  rdflib.RDF.value, rdflib.Literal("abc")))

for result in store_memory.triples((None, None, None)):
    print(result)
    print(type(result[-1]))
    print(list(result[-1]))

for result in store_oxigraph.triples((None, None, None)):
    print(result)
    print(type(result[-1]))
    print(list(result[-1]))

print(list(store_memory.contexts()))
print(list(store_oxigraph.contexts()))
```
Running the script returns the following:
```
((rdflib.term.URIRef('http://localhost/test'), rdflib.term.URIRef('http://www.w3.org/1999/02/22-rdf-syntax-ns#value'), rdflib.term.Literal('abc')), <generator object Memory.__contexts.<locals>.<genexpr> at 0x7f99d9182b20>)
<class 'generator'>
[<Graph identifier=N23e5906f29bb4dceb6ec218e6fd1deb7 (<class 'rdflib.graph.Graph'>)>]

((rdflib.term.URIRef('http://localhost/test'), rdflib.term.URIRef('http://www.w3.org/1999/02/22-rdf-syntax-ns#value'), rdflib.term.Literal('abc', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#string'))), rdflib.term.BNode('N96ef0c76928d439f8d24dc7d59c5d53e'))
<class 'rdflib.term.BNode'>
['N', '9', '6', 'e', 'f', '0', 'c', '7', '6', '9', '2', '8', 'd', '4', '3', '9', 'f', '8', 'd', '2', '4', 'd', 'c', '7', 'd', '5', '9', 'c', '5', 'd', '5', '3', 'e']

[<Graph identifier=N23e5906f29bb4dceb6ec218e6fd1deb7 (<class 'rdflib.graph.Graph'>)>]
[rdflib.term.BNode('N96ef0c76928d439f8d24dc7d59c5d53e')]
```

Some preliminary ideas how this could be solved:
- The triples method needs to be modified to return an iterator over contexts as second element. I think the tricky part is to do this in an efficient way (maybe something like `tuples_with_context.sort()` and `itertools.groupby(tuples_with_context, lambda t: t[0])` would work but I feel this is very inefficient).
- The `_from_ox` method needs to be modified to sometimes return a graph object. Maybe this does require that we keep a map with graph identifiers and graphs somewhere (like `__context_obj_map` in rdflib.plugins.stores.memory.Memory)?

**Comment by Tpt** [comment]
@lukasmu Thank you so much for this amzing bug report. I have written what might be a fix in #29.

I made some design choices that might be bad (feedback very welcomed):
- For `triples()` I do not aggregate the context so a triple might occure multiple time with different contexts. I am not sure how bad it is but it makes implementation easier and allows to skip an aggregation step.
- I do not cache the graph ID -> `Graph` object mapping. I don't know if it's a bad idea or not.
