### ISSUE TITLE
Persisted store shows zero triples

### ISSUE THREAD

**Issue by dymil** [oxigraph/oxrdflib#31]
I'm probably just misunderstanding RDFLib (e.g., identifiers) or my data is funky, but when I try to open a persisted store with identifiers and the like, but when I try to open a previously-persisted store, following the example in the oxrdflib API tutorial, I get zero triples.
For example, the following works:
```
g = Graph(store='Oxigraph')
g.open(dir)
g.parse(ttl_path)
print(len(g))
g.close()
```
and has no errors to suggest it failed to persist, but if I comment out the `parse` call, the length is zero.

`create=True` doesn't seem to make a difference, and adding an identifier to the `Graph` call produces a different error when it comes time to parse: `No scheme found in an absolute IRI`.

I'm using the stable version of RDFLib (6.3.2) and am trying to use this with [YAGO 4.5](https://yago-knowledge.org/downloads/yago-4-5), with the smaller schema and taxonomy files showing this issue, not just the huge facts one which motivated using a more-efficient store.

**Comment by Tpt** [comment]
@ dymil  Thank you for trying Oxigraph! Yes, identifiers in RDFlib is a mess.

> and adding an identifier to the Graph call produces a different error when it comes time to parse: No scheme found in an absolute IRI.

This is probably because you are not using a valid URL (aka IRI) as identifier. Something like `http://example.com/` should work. 

For example
```python
g = Graph(store='Oxigraph', identifier="http://example.com")
g.open(dir)
g.parse(ttl_path)
print(len(g))
g.close()
```

**Comment by Tpt** [comment]
Great!

> Should the code in the README under "If you want to get the store data persisted on disk" have an identifier in the Graph() call?

Yes, definitely.

> Also, do you know if there's some way to avoid re-parsing everything?

Yes, you just need to figure out which auto-generated identifier was used during loading.

Something like `g.query("SELECT ?graph WHERE { GRAPH ?graph { ?s ?p ?o }} LIMIT 1")` should give you the used graph name. If it's a blank node you should use `Graph(store='Oxigraph', identifier=BNode("my_Id"))` afterward to make it work.

**Comment by dymil** [comment]
Worked again, thanks so much!
