### ISSUE TITLE
Contribute Store implementations to rdflib

### ISSUE THREAD

**Issue by nicholascar** [oxigraph/oxrdflib#6]
Should the store implementations used here, `OxMemory` & `OxSled` be listed in rdflib?

I (an rdflib maintainer) would like to make a listing of any rdflib Store implementations, including variants that have other purposes, such as `OxMemory` having varying `Memory` for the purpose of _pyoxigraph_ support, so I'd be keen to list these two.

I might extend the Store listing page within the RDFlib documentation (https://rdflib.readthedocs.io/en/stable/plugin_stores.html) to include Stores external to the main module, like these. Does this sound sensible?

**Comment by Tpt** [comment]
It would be amazing! Thank you!

I plan to release soon a v0.3 that would only contained the `OxSled`  store renamed as `Oxigraph` (Sled uses in-memory temp files when it not explicitely opened on a specific directory so it does not harms too much performances). It might be nice to wait for this v0.3 to list Oxigraph in rdflib documentation. What do you think about it?

I also ran into [a problem](https://github.com/RDFLib/rdflib/issues/1396) when implementing Rust-based SPARQL query/update evalution in oxrdflib. This improves very significantly evaluation performances. Feedback would be very much welcome there.

**Comment by nicholascar** [comment]
OK, I'll draft up an extension to the Stores page and include "Oxigraph". You can always change it to suite.

Yes, I saw your problem. I'll look into it in more depth shortly.

**Comment by Tpt** [comment]
Great! Thank you!

**Comment by Tpt** [comment]
It seems to have been done. Thank you!
