### ISSUE TITLE
[Feature Request] Rename NamedGraph (from Python)?

### ISSUE THREAD

**Issue by ashleysommer** [oxigraph/oxrdflib#65]
I'm not sure if this is a support question or a feature request, perhaps both.

I am in the situation where I need to transform from State A, to State B:

```trig
# trig "stateA.trig"
:GraphA {
    :S :P :O # 1 million triples
}
:OtherGraph {} # Many other named graphs exist
```

```trig
# trig "stateB.trig"
:GraphB { # renamed NamedGraph
    :S :P :O # Same 1 million triples
}
:OtherGraph {} # Other named graphs don't change
```

Currently I'm doing the following operation in PyOxigraph:

```python
def rename_named_graph(store: pyoxigraph.Store, old_name: str, new_name: str):
    old_named_node = pyoxigraph.NamedNode(old_name)
    new_named_node = pyoxigraph.NamedNode(new_name)
    store.add_graph(new_named_node)
    for (s, p, o, g) in store.quads_for_pattern(None, None, None, old_named_node):
        store.add(pyoxigraph.Quad(s, p, o, new_named_node))
    store.remove_graph(old_named_node)
```
I'm concerned this is not very efficient, because we need to convert every quad to a Python object, and create a new Quad object for every triple, and push it back to the store.

Other options I've thought of are:
1) Dump to intermediate file, and use from_graph and to_graph to switch the graph name.
```python
def rename_named_graph(store: pyoxigraph.Store, old_name: str, new_name: str):
    old_named_node = pyoxigraph.NamedNode(old_name)
    new_named_node = pyoxigraph.NamedNode(new_name)
    store.dump("intermediate.nt", pyoxigraph.RdfFormat.N_TRIPLES, from_graph=old_named_node)
    store.add_graph(new_named_node)
    store.remove_graph(old_named_node)
    store.load("intermediate.nt", pyoxigraph.RdfFormat.N_TRIPLES, to_graph=new_named_node)
```
2) Just use a sparql update query:
```sparql
DELETE {
    GRAPH <GraphA> {
        ?s ?o ?o .
    }
}
INSERT {
    GRAPH <GraphB> {
        ?s ?p ?o .
    }
}
WHERE {
    GRAPH <GraphA> {
        ?s ?o ?o .
    }
}
```

**Comment by Tpt** [comment]
Hey! The [SPARQL update `MOVE` command](https://www.w3.org/TR/sparql11-update/#move) is maybe what you are looking for:

```sparql
MOVE GRAPH <GraphA> TO GRAPH <GraphB>
```

**Comment by ashleysommer** [comment]
Hi @Tpt 
Thanks for the response.
I've honestly never even seen or heard of the SPARQL "MOVE" commend before. Thanks for pointing that out.
And I didn't think of using the ADD command like that either. So this can be closed now.
