### ISSUE TITLE
Usage in RDFLib > 6

### ISSUE THREAD

**Issue by neobernad** [oxigraph/oxrdflib#7]
Hello,

I am trying to use `oxrdflib` for an `rdflib` version > 6. I have seen that there is a restriction that `oxrdflib` is only usable for `rdflib<6.0,>=4.0`.

Is there any upgrade in the roadmap?

Thanks,
José Antonio

**Comment by Tpt** [comment]
Hi! I have just released [v0.2.1](https://github.com/oxigraph/oxrdflib/releases/tag/v0.2.1) that adds compatibility with rdflib 6.
